[build]
  command = "# No build command needed for static site"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "echo 'Starting local dev server'"
  targetPort = 8888
  publish = "."
  framework = "#static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

